### ISSUE TITLE
Bug in draft-release-notes.py when handling colon in summary text

### ISSUE THREAD

**Issue by arhag** [ericpassmore/helpers#1]
I believe there is bug here: https://github.com/ericpassmore/helpers/blob/999637eae2ba14014be355bf7e037fdd9f122b5f/git/draft-release-notes.py#L219-L225

Particularly, when capturing the summary from the properly formatted GitHub comment on a PR, it seems that if the summary has a `:` in it, then it will truncate the rest of the summary on that line.

Examples of this appear to have been seen in practice when preparing Spring 1.0 release notes. Two concrete examples I can point to are the following:

https://github.com/antelopeIO/leap/pull/2390#issuecomment-2048322136 (content reproduced below)
> Note:start 
> group: RELEASE 
> category: CHORE 
> summary: CICD: use github provided token for git in submodule regression check. 
> Note:end

and 

https://github.com/antelopeIO/spring/pull/149#issuecomment-2117934427 (content reproduced below)

> Note:start 
> group: IF 
> category: BUG 
> summary: P2P: Fix switch from lib catchup to head catchup. Fixes bug which incorrectly assumed blocks in dispatcher list were applied.
> Note:end

**Comment by ericpassmore** [comment]
Hah, yes long standing bug. Now fixed with commit 2a53af3629ab1e12d18fb425c40552c7b8f153c8 to main. 
![Screenshot 2024-09-04 at 6 05 46 PM](https://github.com/user-attachments/assets/f4108756-2edb-443d-ba29-f842578ede44)
